
name: publish investigations
on:
  push:
    branches: ["main"]
    paths:
      - 'published/**'
      - 'useful_scripts/generate_index.py'
      - 'useful_scripts/templates/**'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: install jinja2
        run: pip install jinja2
      - name: generate index
        run: python useful_scripts/generate_index.py
      - name: setup pages
        uses: actions/configure-pages@v5
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'published'
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
