name: Python package

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.11
          cache: true

      - name: install packages
        run: |
          pip install pdm
          pdm install --no-lock -v
        
      - name: run tests
        run: |
          source .venv/bin/activate
          coverage run -m pytest
          coverage report
