name: Python package

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: install python and packages
        run: uv sync --locked --all-extras --dev
        
      - name: run tests
        run: |
          source .venv/bin/activate
          coverage run -m pytest
          coverage report
